### ISSUE TITLE
How to fix this U2U1017?

### ISSUE THREAD

**Issue by wmjordan** [u2uconsult/codeanalyzers#10]
The `U2U1017` message is helpful.

However it provides a false suggestion in the following method, which triggers `1017` at the line where `p` is initialized.
Since the subsequent `stream.Read` call changes the position, moving the initialization of `p` into the `if` statement could break the code.

````C#
public static void CopyTo(this Stream stream, Stream target, int bufferSize) {
	var b = new byte[bufferSize];
	var p = stream.Position; // triggers 1017 mistakenly
	int c;
	while ((c = stream.Read(b, 0, bufferSize)) > 0) {
		target.Write(b, 0, c);
	}
	if (stream.CanSeek) {
		stream.Position = p;
	}
}
````

**Comment by KrisVandermotten** [comment]
You can't fix it. You can suppress it with a [pragma directive](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning), or you can simply ignore the informational (not a warning!) message.

Note that the message says "*It seems that* the variable 'p' is only used in the if statement on line {n} when the condition is 'true'; *consider* initializing the variable there". In this case it turns out you can't initialize it there, but the analyzer can't figure that out (as it does not know that calling `stream.Read()` will modify `stream.Position`).

**Comment by wmjordan** [comment]
Alright, it is really a tough task.
