### ISSUE TITLE
U2U1100: Compare strings correctly

### ISSUE THREAD

**Issue by SergerGood** [u2uconsult/codeanalyzers#28]
`public class ToMeasure
    {
        string a = "";
        string b = "b";
        string c = null;

        bool r;

        [Benchmark]
        public void EqualsString()
        {
            r = a == "" | b == "" | c == "";
        }

        [Benchmark(Baseline = true)]
        public void EqualsLength()
        {
            r = a?.Length == 0 | b?.Length == 0 | c?.Length == 0;
        }

        [Benchmark]
        public void EqualsEmpty()
        {
            r = string.IsNullOrEmpty(a) | string.IsNullOrEmpty(b) | string.IsNullOrEmpty(c);
        }
    }`

`BenchmarkDotNet=v0.12.0, OS=Windows 10.0.17134.1246 (1803/April2018Update/Redstone4)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
  Job-ZMJTGQ : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT

Platform=X64  Toolchain=.NET Core 3.1  IterationCount=3
LaunchCount=1  WarmupCount=0

|       Method |      Mean |     Error |    StdDev | Ratio | RatioSD | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |----------:|----------:|----------:|------:|--------:|------:|------:|------:|----------:|
| EqualsString | 6.0126 ns | 0.7909 ns | 0.0434 ns |  4.74 |    0.21 |     - |     - |     - |         - |
| EqualsLength | 1.2714 ns | 1.1238 ns | 0.0616 ns |  1.00 |    0.00 |     - |     - |     - |         - |
|  EqualsEmpty | 0.8025 ns | 0.3515 ns | 0.0193 ns |  0.63 |    0.02 |     - |     - |     - |         - |`

**Comment by KrisVandermotten** [comment]
I'm not sure what you're trying to say?

Your test confirms that `s?.Length == 0` is a lot faster than `s == ""`.

Your comparison with `string.IsNullOrEmpty(s)` is not relevant, as it does not do the same thing.

Indeed:

    > string s = null;
    > s == ""
    false
    > s?.Length == 0
    false
    > string.IsNullOrEmpty(s)
    true

`s?.Length == 0` means `s != null && s.Length == 0`.
`string.IsNullOrEmpty(s)` means `s == null || s.Length == 0`.

**Comment by SergerGood** [comment]
Yes, but we want to compare with an empty string and not null. Therefore, the choice method `string.IsNullOrEmpty(s)` looks more optimal.

**Comment by KrisVandermotten** [comment]
Again, `string.IsNullOrEmpty(s)` simply does not do the same thing as `s == ""`, so comparing the speed of both is pointless. Just to illustrate my point: I'm guessing that `s == s` will also be faster than `s == ""`, but that too is not relevant, because it also doesn't do the same thing.

On the other hand, `s == ""` and `s?.Length == 0` are truly equivalent. If one is true, so is the other. If one is false, so is the other. They do mean the exact same thing.

Secondly, you have no evidence for your claim that `string.IsNullOrEmpty(s)` is faster than `s?.Length == 0`.

Your microbenchmark reports 1.2714 ns with a 1.1238 ns error for `s?.Length == 0`. Somewhat simplified, that means the real value might be as low as 1.2714 - 1.1238 = 0.1476 ns. For `string.IsNullOrEmpty(s)`, it reports 0.8025 ns with a 0.3515 ns error, which means the real value might be as high as 0.8025 + 0.3515 = 1.1540 ns. As you can see, 1.1540 is a lot more than 0.1476, so you have no evidence that it is faster.

Note also that the results of your microbenchmark depend on the relative frequency of the values. You have the same number of null values, "" values and non-null non-empty values. In a real application, the distribution of the different values would probably be different. What that means is that your benchmark, even if its results were clear, doesn't say much about any real application.

BTW, if in your application you already know that `s != null`, then `s == ""` is equivalent to `s.Length == 0`, which would in that case be faster than `string.IsNullOrEmpty(s)`.

Finally, we're not telling you what code to write, we're only telling you that expressions like `s == ""` can be replaced by an alternative expression, that does the same thing more efficiently, even though it is more difficult te read. If you're not happy with `s?.Length == 0` or your team members have difficulty understanding it, then don't use it. Stick with `s == ""`.

**Comment by SergerGood** [comment]
https://github.com/dotnet/runtime/blob/a80e6d4c69fcfa1e17e17130c144a567b23a12a9/src/libraries/System.Private.CoreLib/src/System/String.cs#L434

**Using 0u >= (uint)value.Length rather than value.Length == 0 as it will elide the bounds check to the first char: value[0] if that is performed following the test for the same test cost.**
